from src.core.config.public import *

class user(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    password = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    age = models.FloatField(default=0)
    salary = models.FloatField(default=0)
    ip = models.CharField(max_length=255, null=True, blank=True)
    host = models.CharField(max_length=255, null=True, blank=True)
    date = models.CharField(max_length=255, null=True, blank=True)
    notes = models.CharField(max_length=255, null=True, blank=True)
    image = models.CharField(max_length=255, default="default.png")
    role = models.IntegerField(default=1)
    super = models.BooleanField(default=False)
    chat = models.BooleanField(default=False)
    mail = models.BooleanField(default=False)
    users = models.BooleanField(default=False)
    categories = models.BooleanField(default=False)
    products = models.BooleanField(default=False)
    orders = models.BooleanField(default=False)
    coupons = models.BooleanField(default=False)
    articles = models.BooleanField(default=False)
    contacts = models.BooleanField(default=False)
    settings = models.BooleanField(default=False)
    statistics = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

class mail(models.Model):
    sender = models.IntegerField(default=0)
    receiver = models.IntegerField(default=0)
    title = models.TextField(default="")
    description = models.TextField(default="")
    display_text = models.TextField(default="")
    date = models.CharField(max_length=255, blank=True, null=True)
    remove_sender = models.BooleanField(default=False)
    remove_receiver = models.BooleanField(default=False)
    see_sender = models.BooleanField(default=True)
    see_receiver = models.BooleanField(default=False)
    important_sender = models.BooleanField(default=False)
    star_sender = models.BooleanField(default=False)
    important_receiver = models.BooleanField(default=False)
    star_receiver = models.BooleanField(default=False)

class file(models.Model):
    mail_id = models.IntegerField(default=0)
    product_id = models.IntegerField(default=0)
    article_id = models.IntegerField(default=0)
    name = models.CharField(max_length=255, blank=True, null=True)
    type = models.CharField(max_length=255, blank=True, null=True)
    size = models.CharField(max_length=255, blank=True, null=True)
    link = models.CharField(max_length=255, blank=True, null=True)
    date = models.CharField(max_length=255, blank=True, null=True)

class friend(models.Model):
    person_1 = models.IntegerField(default=0)
    person_2 = models.IntegerField(default=0)
    date = models.CharField(max_length=255, null=True, blank=True)
    update = models.CharField(max_length=255, null=True, blank=True)
    remove_1 = models.BooleanField(default=False)
    remove_2 = models.BooleanField(default=False)

class chat(models.Model):
    sender = models.IntegerField(default=0)
    receiver = models.IntegerField(default=0)
    type = models.CharField(max_length=255, blank=True, null=True)
    link = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    size = models.CharField(max_length=255, blank=True, null=True)
    date = models.CharField(max_length=255, blank=True, null=True)
    content = models.TextField(default="")
    remove_sender = models.BooleanField(default=False)
    remove_receiver = models.BooleanField(default=False)
    see_sender = models.BooleanField(default=False)
    see_receiver = models.BooleanField(default=False)

class setting(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    url = models.CharField(max_length=255, null=True, blank=True)
    language = models.CharField(max_length=255, null=True, blank=True)
    facebook = models.CharField(max_length=255, null=True, blank=True)
    whatsapp = models.CharField(max_length=255, null=True, blank=True)
    twetter = models.CharField(max_length=255, null=True, blank=True)
    telegram = models.CharField(max_length=255, null=True, blank=True)
    youtube = models.CharField(max_length=255, null=True, blank=True)
    instagram = models.CharField(max_length=255, null=True, blank=True)
    linkedin = models.CharField(max_length=255, null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    theme = models.CharField(max_length=255, default="dark")
    image = models.CharField(max_length=255, default="default.png")
    enable_register = models.BooleanField(default=True)
    enable_login = models.BooleanField(default=True)
    enable_contacts = models.BooleanField(default=True)
    enable_orders = models.BooleanField(default=True)
    enable_chat = models.BooleanField(default=True)
    enable_chat_files = models.BooleanField(default=True)
    deactive = models.BooleanField(default=False)

class contact(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    ip = models.CharField(max_length=255, null=True, blank=True)
    host = models.CharField(max_length=255, null=True, blank=True)
    date = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)

class category(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    date = models.CharField(max_length=255, null=True, blank=True)
    image = models.CharField(max_length=255, default="default.png")
    products = models.BooleanField(default=True)
    active = models.BooleanField(default=True)

class product(models.Model):
    category_id = models.IntegerField(default=0)
    name = models.CharField(max_length=255, null=True, blank=True)
    keys = models.CharField(max_length=255, null=True, blank=True)
    attraction = models.CharField(max_length=255, null=True, blank=True)
    company = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    times = models.TextField(null=True, blank=True)
    time = models.CharField(max_length=255, null=True, blank=True)
    included = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    overview = models.TextField(null=True, blank=True)
    policy = models.TextField(null=True, blank=True)
    meeting = models.TextField(null=True, blank=True)
    expect = models.TextField(null=True, blank=True)
    info = models.TextField(null=True, blank=True)
    old_price = models.FloatField(default=0)
    new_price = models.FloatField(default=0)
    reviews = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    adults = models.IntegerField(default=0)
    rate = models.FloatField(default=0)
    bookings = models.IntegerField(default=0)
    date = models.CharField(max_length=255, null=True, blank=True)
    notes = models.CharField(max_length=255, null=True, blank=True)
    image = models.CharField(max_length=255, default="default.png")
    allow_bookings = models.BooleanField(default=True)
    cancellation = models.BooleanField(default=True)
    pay_later = models.BooleanField(default=True)
    public = models.BooleanField(default=True)
    active = models.BooleanField(default=True)

class order(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    notes = models.CharField(max_length=255, null=True, blank=True)
    user_id = models.IntegerField(default=0)
    product_id = models.IntegerField(default=0)
    adults = models.IntegerField(default=0)
    price = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    date = models.CharField(max_length=255, null=True, blank=True)
    book_date = models.CharField(max_length=255, null=True, blank=True)
    book_time = models.CharField(max_length=255, null=True, blank=True)
    pick_up = models.CharField(max_length=255, null=True, blank=True)
    coupon = models.CharField(max_length=255, null=True, blank=True)
    paid = models.BooleanField(default=False)
    status = models.IntegerField(default=1)
    removed = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

class coupon(models.Model):
    code = models.CharField(max_length=255, null=True, blank=True)
    discount = models.FloatField(default=0)
    date = models.CharField(max_length=255, null=True, blank=True)
    active = models.BooleanField(default=True)

class article(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    date = models.CharField(max_length=255, null=True, blank=True)
    notes = models.CharField(max_length=255, null=True, blank=True)
    image = models.CharField(max_length=255, default="default.png")
    active = models.BooleanField(default=True)

class reset(models.Model):
    user_id = models.IntegerField(default=0)
    token = models.TextField(null=True, blank=True)
    date = models.CharField(max_length=255, null=True, blank=True)
    active = models.BooleanField(default=True)

class payment(models.Model):
    user_id = models.IntegerField(default=0)
    tour_id = models.IntegerField(default=0)
    order_id = models.IntegerField(default=0)
    adults = models.IntegerField(default=0)
    real_price = models.FloatField(default=0)
    paid_price = models.FloatField(default=0)
    paid_secret = models.CharField(max_length=255, null=True, blank=True)
    paid_date = models.CharField(max_length=255, null=True, blank=True)
    date = models.CharField(max_length=255, null=True, blank=True)
